package buntatsun.cdt.proc;

public class ProCKeywords {
	public static final char[]
			rh_oraca_h = "oraca.h".toCharArray(),
			rh_sqlca_h = "sqlca.h".toCharArray(),
			rh_sqlda_h = "sqlda.h".toCharArray(),
			rh_ORACA_H = "ORACA.H".toCharArray(),
			rh_SQLCA_H = "SQLCA.H".toCharArray(),
			rh_SQLDA_H = "SQLDA.H".toCharArray(),
			rh_ORACA = "ORACA".toCharArray(),
			rh_SQLCA = "SQLCA".toCharArray(),
			rh_SQLDA = "SQLDA".toCharArray(),
			rh_oraca = "oraca".toCharArray(),
			rh_sqlca = "sqlca".toCharArray(),
			rh_sqlda = "sqlda".toCharArray(),

			cp_EXEC = "EXEC".toCharArray(),
			cp_exec = "exec".toCharArray(),
			cp_ORACLE = "ORACLE".toCharArray(),
			cp_oracle = "oracle".toCharArray(),
			cp_SQL = "SQL".toCharArray(),
			cp_sql = "sql".toCharArray(),
			cp_INCLUDE = "INCLUDE".toCharArray(),
			cp_include = "include".toCharArray(),
			cp_BEGIN = "BEGIN".toCharArray(),
			cp_begin = "begin".toCharArray(),
			cp_END = "END".toCharArray(),
			cp_end = "end".toCharArray(),
			cp_DECLARE = "DECLARE".toCharArray(),
			cp_declare = "declare".toCharArray(),
			cp_SECTION = "SECTION".toCharArray(),
			cp_section = "section".toCharArray(),
			cp_CURSOR = "CURSOR".toCharArray(),
			cp_cursor = "cursor".toCharArray(),
			cp_FOR = "FOR".toCharArray(),
			cp_for = "for".toCharArray(),
			cp_OPEN = "OPEN".toCharArray(),
			cp_open = "open".toCharArray(),
			cp_CLOSE = "CLOSE".toCharArray(),
			cp_close = "close".toCharArray(),
			cp_FETCH = "FETCH".toCharArray(),
			cp_fetch = "fetch".toCharArray(),
			cp_INTO = "INTO".toCharArray(),
			cp_into = "into".toCharArray(),
			cp_VARCHAR = "VARCHAR".toCharArray(),
			cp_varchar = "varchar".toCharArray(),

			sq_SELECT = "SELECT".toCharArray(),
			sq_select = "select".toCharArray(),
			sq_DELETE = "DELETE".toCharArray(),
			sq_delete = "delete".toCharArray(),
			sq_INSERT = "INSERT".toCharArray(),
			sq_insert = "insert".toCharArray(),
			sq_UPDATE = "UPDATE".toCharArray(),
			sq_update = "update".toCharArray(),
			sq_TRUNCATE = "TRUNCATE".toCharArray(),
			sq_truncate = "truncate".toCharArray()
			;
}
